
help:  ## Show help
	@grep -E '^[.a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'

initialize-fresh: erase-git docker-build init-git ## initialize the development environment (WARNING: This resets the local git repo!)

full-reset-git: erase-git init-git ## delete .git and reinitialize repo with pre-commit settings (WARNING: This resets the local git repo!)

erase-git:
	@read -p "This will remove the existing .git folder and initialize a new repository. Are you sure? (y/N) " confirm && [ "$$confirm" = "y" ] || [ "$$confirm" = "Y" ]
	@read -p "Are you ABOSLUTELY sure? (y/N) " confirm && [ "$$confirm" = "y" ] || [ "$$confirm" = "Y" ]
	@echo "Removing existing .git folder..."
	rm -rf .git

init-git: ## Initialize a fresh git repository (only if one doesn't already exist)
	git init
	git config --global --add safe.directory /workspace
	pre-commit install

docker-build: ## initialize the development environment
	set -o errexit
	export DOCKER_BUILDKIT=1
	export PROGRESS_NO_TRUNC=1
	@echo "Building Docker container..."
	docker build --tag "$(shell basename $(shell pwd)):latest" \
		--build-arg OS_VERSION="22.04" \
		--build-arg CUDA_VERSION="12.4.1" \
		--build-arg PYTHON_VERSION="3.11" \
		--build-arg USER_ID=$(shell id -u) \
		--build-arg GROUP_ID=$(shell id -g) \
		--build-arg NAME=$(shell whoami) \
		--build-arg WORKDIR_PATH=$(shell pwd) .


clean: ## Clean autogenerated files
	rm -rf dist
	find . -type f -name "*.DS_Store" -ls -delete
	find . | grep -E "(__pycache__|\.pyc|\.pyo)" | xargs rm -rf
	find . | grep -E ".pytest_cache" | xargs rm -rf
	find . | grep -E ".ipynb_checkpoints" | xargs rm -rf
	rm -f .coverage

clean-logs: ## Clean logs
	rm -rf logs/**

format: ## Run pre-commit hooks
	pre-commit run -a

sync: ## Merge changes from main branch to your current branch
	git pull
	git pull origin main

test: ## Run not slow tests
	pytest -k "not slow"

test-full: ## Run all tests
	pytest

train: ## Train the model
	docker run --runtime=nvidia --gpus all \
		--rm -it \
	    -v "$(shell pwd)":/workspace \
	    -w /workspace \
	    train-transformer:latest \
	    scripts/train.sh $(ARGS)
